# Generated by Django 3.2.6 on 2021-09-01 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_invoice_client_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='client_zipcpde',
            new_name='client_zipcode',
        ),
    ]
